import type { NextPage } from 'next'
import Head from 'next/head'
import styled from '@emotion/styled'
import { useEffect, useState } from 'react'
import Dropdown from '@elements/Dropdown'
import { queueArray } from '@constant/Queue'
import TopInfo from '@components/TopInfo'
import { useSummoner } from '@hooks/useSummoner'
import { useRouter } from 'next/router'
import Hr from '@elements/Hr'
import BottomTable from '@components/BottomTable'
import { queryClient } from '@pages/_app'

const Summoner: NextPage = () => {
  const router = useRouter()
  const { summoner } = router.query

  const [name, setName] = useState('')
  const [matchCategory, setMatchCategory] = useState('SoloRank')
  const [lane, setLane] = useState(null)
  const [champion, setChampion] = useState(null)

  const { data } = useSummoner({ summoner, matchCategory, champion, lane })

  useEffect(() => {
    if (data) setName(data.name)
    console.log(data)
  }, [data])

  useEffect(() => {
    queryClient
      .invalidateQueries([summoner, {}])
      .then((res) => {
        console.log(res)
      })
      .catch((err) => {
        console.log(err)
      })
  }, [lane, champion])

  return (
    <div className="global">
      <Head>
        <title>{name} | 검색결과</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <H1>{name || summoner}</H1>

      <div className="flex-s">
        <Dropdown long items={queueArray} setState={setMatchCategory}>
          {matchCategory}
        </Dropdown>
      </div>

      <TopInfo data={data} />
      <Hr />

      <BottomTable data={data} setLane={setLane} setChampion={setChampion} />
    </div>
  )
}

const H1 = styled.h1`
  font-size: ${({ theme }) => theme.font.font1};
  font-weight: 700;
  margin: 0 0 17px;
  text-align: center;
`

export default Summoner
