import React, { useState } from 'react'
import Link from 'next/link'
import { NextPage } from 'next'
import Title from '@components/Title'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="global title-global">
      <Head>
        <title>your.gg 테스트 - 이한울</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex-c-c">
        <Title />
      </div>
    </div>
  )
}

export default Home
